### PR TITLE
Initial site templating, for test PR

### PR DESCRIPTION
**Pull request by arm22**
Basic page layout with minimal content/style. Wanted to get a PR in to make sure things are working.

### CODE REVIEW

**Comment by fiannaca** [comment]
@arm22 Before I can merge this pull request, you need to update your master branch and rebase you jrny branch based on the updated master branch. See the instructions I posted on Canvas for rebasing.

**Comment by fiannaca** [comment]
@arm22 I just squashed your commits and merged them. Make sure to up update your fork and create a new feature branch  to work out of before making more changes

**Comment by arm22** [comment]
@fiannaca I was working off of the development instructions, I must have missed the announcement about rebasing. It looks like there are some issues with the styling so I will make sure to follow those instructions as I fix those issues and continue editing. Thanks for the help!

**Comment by fiannaca** [comment]
@arm22 sorry, I should have been more clear in the dev instructions. You should always rebase right before the pushing and creating a pull request, so that your pull request is up to date with the latest changes in master. This prevents merge conflicts and keeps the git history clean

**Pull request merged**
